// <auto-generated />
using System;
using ITIExaminationSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITIExaminationSystem.Migrations
{
    [DbContext(typeof(ExaminationSystemContext))]
    partial class ExaminationSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnswerSelectedChoice", b =>
                {
                    b.Property<int>("AnswerId")
                        .HasColumnType("int")
                        .HasColumnName("Answer_Id");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int")
                        .HasColumnName("Choice_Id");

                    b.HasKey("AnswerId", "ChoiceId")
                        .HasName("PK__Answer_S__8BFD02979955B5C0");

                    b.HasIndex("ChoiceId");

                    b.ToTable("Answer_Selected_Choices", (string)null);
                });

            modelBuilder.Entity("BranchTrack", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    b.HasKey("BranchId", "TrackId")
                        .HasName("PK__Branch_T__E714720B152DF829");

                    b.HasIndex("TrackId");

                    b.ToTable("Branch_Track", (string)null);
                });

            modelBuilder.Entity("ExamQuestion", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_Id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.HasKey("ExamId", "QuestionId")
                        .HasName("PK__Exam_Que__BC89E417FCCD2AF7");

                    b.HasIndex("QuestionId");

                    b.ToTable("Exam_Questions", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Admin_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__4A3006F760C3DE7A");

                    b.HasIndex(new[] { "UserId" }, "UQ__Admin__206D9171021E5F58")
                        .IsUnique()
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Answer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_Id");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int?>("ScoredMarks")
                        .HasColumnType("int")
                        .HasColumnName("Scored_Marks");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    b.Property<bool?>("TfSelected")
                        .HasColumnType("bit")
                        .HasColumnName("TF_Selected");

                    b.HasKey("AnswerId")
                        .HasName("PK__Answer__36918F389C12DAC8");

                    b.HasIndex("ExamId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Assign", b =>
                {
                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_Id");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("Instructor_Id");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    b.HasKey("ExamId", "InstructorId", "BranchId", "TrackId")
                        .HasName("PK_Assign_New");

                    b.HasIndex("BranchId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TrackId");

                    b.ToTable("Assign", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Branch_Location");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Branch_Name");

                    b.HasKey("BranchId")
                        .HasName("PK__Branch__12CEB061AD589742");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.BranchManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Manager_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("ManagerId")
                        .HasName("PK__Branch_M__AE5FEFAD89C7F12F");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Branch_Manager", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Choice_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoiceId"));

                    b.Property<string>("ChoiceText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Choice_Text");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.HasKey("ChoiceId")
                        .HasName("PK__Choice__D6C8DAFAFF01FA83");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choice", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Course_Name");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int?>("TriesLimit")
                        .HasColumnType("int")
                        .HasColumnName("Tries_Limit");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__37E005DB603B40BB");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Exam_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<int?>("FullMarks")
                        .HasColumnType("int")
                        .HasColumnName("Full_Marks");

                    b.Property<int>("QuestionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time");

                    b.HasKey("ExamId")
                        .HasName("PK__Exam__C782CA59A3A9FB14");

                    b.HasIndex("CourseId");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Instructor_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("InstructorId")
                        .HasName("PK__Instruct__DD4B9AEAE6A8A24C");

                    b.HasIndex(new[] { "UserId" }, "UQ__Instruct__206D91715F36F848")
                        .IsUnique()
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<bool?>("CorrectTf")
                        .HasColumnType("bit")
                        .HasColumnName("Correct_TF");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("Instructor_Id");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Question_Text");

                    b.Property<string>("QuestionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Question_Type");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__B0B2E4E64CCE7EB8");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Solve", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("Exam_Id");

                    b.Property<int?>("TrialNumber")
                        .HasColumnType("int")
                        .HasColumnName("Trial_Number");

                    b.HasKey("StudentId", "CourseId", "ExamId")
                        .HasName("PK__Solve__2E8CC52939432065");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExamId");

                    b.ToTable("Solve", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    b.Property<int?>("IntakeNumber")
                        .HasColumnType("int")
                        .HasColumnName("Intake_Number");

                    b.Property<int?>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__A2F4E98CC78B11FB");

                    b.HasIndex("BranchId");

                    b.HasIndex("TrackId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Student__206D91713C485A67")
                        .IsUnique()
                        .HasFilter("[User_Id] IS NOT NULL");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Teach", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_Id");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("Instructor_Id");

                    b.Property<int>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    b.Property<bool?>("IsSupervisor")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Supervisor");

                    b.HasKey("CourseId", "BranchId", "InstructorId", "TrackId")
                        .HasName("PK__Teach__DD11A547E6AC0E77");

                    b.HasIndex("BranchId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TrackId");

                    b.ToTable("Teach", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Topic_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.Property<string>("TopicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Topic_Name");

                    b.HasKey("TopicId")
                        .HasName("PK__Topic__8DEAA405428BF83B");

                    b.HasIndex("CourseId");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("TrackName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Track_Name");

                    b.HasKey("TrackId")
                        .HasName("PK__Track__5DAC26AE6C203B0A");

                    b.ToTable("Track", (string)null);
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("User_Email");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("User_Name");

                    b.Property<string>("UserPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("User_Password");

                    b.HasKey("UserId")
                        .HasName("PK__User__206D9170ED1EC7C3");

                    b.HasIndex(new[] { "UserEmail" }, "UQ__User__4C70A05C7FFFAF06")
                        .IsUnique()
                        .HasFilter("[User_Email] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("QuestionCorrectChoice", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int")
                        .HasColumnName("Choice_Id");

                    b.HasKey("QuestionId", "ChoiceId")
                        .HasName("PK__Question__0DDE69496828E75B");

                    b.HasIndex("ChoiceId");

                    b.ToTable("Question_Correct_Choices", (string)null);
                });

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_Id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.HasKey("StudentId", "CourseId")
                        .HasName("PK__Student___018AE9D1D0EA719D");

                    b.HasIndex("CourseId");

                    b.ToTable("Student_Course", (string)null);
                });

            modelBuilder.Entity("TrackCourse", b =>
                {
                    b.Property<int>("TrackId")
                        .HasColumnType("int")
                        .HasColumnName("Track_Id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("Course_Id");

                    b.HasKey("TrackId", "CourseId")
                        .HasName("PK__Track_Co__FED226F3995B4287");

                    b.HasIndex("CourseId");

                    b.ToTable("Track_Course", (string)null);
                });

            modelBuilder.Entity("AnswerSelectedChoice", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Answer", null)
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .IsRequired()
                        .HasConstraintName("FK__Answer_Se__Answe__7A672E12");

                    b.HasOne("ITIExaminationSystem.Models.Choice", null)
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Answer_Se__Choic__7B5B524B");
                });

            modelBuilder.Entity("BranchTrack", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Branch_Tr__Branc__4D94879B");

                    b.HasOne("ITIExaminationSystem.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Branch_Tr__Track__4E88ABD4");
                });

            modelBuilder.Entity("ExamQuestion", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam_Ques__Exam___71D1E811");

                    b.HasOne("ITIExaminationSystem.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__Exam_Ques__Quest__72C60C4A");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Admin", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("ITIExaminationSystem.Models.Admin", "UserId")
                        .HasConstraintName("FK__Admin__User_Id__3B75D760");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Answer", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Exam", "Exam")
                        .WithMany("Answers")
                        .HasForeignKey("ExamId")
                        .HasConstraintName("FK__Answer__Exam_Id__76969D2E");

                    b.HasOne("ITIExaminationSystem.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Answer__Question__778AC167");

                    b.HasOne("ITIExaminationSystem.Models.Student", "Student")
                        .WithMany("Answers")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Answer__Student___75A278F5");

                    b.Navigation("Exam");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Assign", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Branch", "Branch")
                        .WithMany("Assigns")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Branch");

                    b.HasOne("ITIExaminationSystem.Models.Exam", "Exam")
                        .WithMany("Assigns")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Exam");

                    b.HasOne("ITIExaminationSystem.Models.Instructor", "Instructor")
                        .WithMany("Assigns")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Instructor");

                    b.HasOne("ITIExaminationSystem.Models.Track", "Track")
                        .WithMany("Assigns")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK_Assign_Track");

                    b.Navigation("Branch");

                    b.Navigation("Exam");

                    b.Navigation("Instructor");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.BranchManager", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Branch", "Branch")
                        .WithMany("BranchManagers")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK__Branch_Ma__Branc__4AB81AF0");

                    b.HasOne("ITIExaminationSystem.Models.User", "User")
                        .WithMany("BranchManagers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Branch_Ma__User___49C3F6B7");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Choice", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__Choice__Question__6B24EA82");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Exam", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Exam__Course_Id__5FB337D6");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Instructor", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.User", "User")
                        .WithOne("Instructor")
                        .HasForeignKey("ITIExaminationSystem.Models.Instructor", "UserId")
                        .HasConstraintName("FK__Instructo__User___3F466844");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Question", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Question__Course__68487DD7");

                    b.HasOne("ITIExaminationSystem.Models.Instructor", "Instructor")
                        .WithMany("Questions")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK__Question__Instru__6754599E");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Solve", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", "Course")
                        .WithMany("Solves")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Solve__Course_Id__7F2BE32F");

                    b.HasOne("ITIExaminationSystem.Models.Exam", "Exam")
                        .WithMany("Solves")
                        .HasForeignKey("ExamId")
                        .IsRequired()
                        .HasConstraintName("FK__Solve__Exam_Id__00200768");

                    b.HasOne("ITIExaminationSystem.Models.Student", "Student")
                        .WithMany("Solves")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Solve__Student_I__7E37BEF6");

                    b.Navigation("Course");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Student", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Branch", "Branch")
                        .WithMany("Students")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("FK_Student_Branch");

                    b.HasOne("ITIExaminationSystem.Models.Track", "Track")
                        .WithMany("Students")
                        .HasForeignKey("TrackId")
                        .HasConstraintName("FK_Student_Track");

                    b.HasOne("ITIExaminationSystem.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("ITIExaminationSystem.Models.Student", "UserId")
                        .HasConstraintName("FK__Student__User_Id__4316F928");

                    b.Navigation("Branch");

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Teach", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Branch", "Branch")
                        .WithMany("Teaches")
                        .HasForeignKey("BranchId")
                        .IsRequired()
                        .HasConstraintName("FK__Teach__Branch_Id__571DF1D5");

                    b.HasOne("ITIExaminationSystem.Models.Course", "Course")
                        .WithMany("Teaches")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Teach__Course_Id__5629CD9C");

                    b.HasOne("ITIExaminationSystem.Models.Instructor", "Instructor")
                        .WithMany("Teaches")
                        .HasForeignKey("InstructorId")
                        .IsRequired()
                        .HasConstraintName("FK__Teach__Instructo__5812160E");

                    b.HasOne("ITIExaminationSystem.Models.Track", "Track")
                        .WithMany("Teaches")
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Teach__Track_Id__59063A47");

                    b.Navigation("Branch");

                    b.Navigation("Course");

                    b.Navigation("Instructor");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Topic", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", "Course")
                        .WithMany("Topics")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Topic__Course_Id__534D60F1");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("QuestionCorrectChoice", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Choice", null)
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Question___Choic__6EF57B66");

                    b.HasOne("ITIExaminationSystem.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK__Question___Quest__6E01572D");
                });

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Student_C__Cours__5CD6CB2B");

                    b.HasOne("ITIExaminationSystem.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__Student_C__Stude__5BE2A6F2");
                });

            modelBuilder.Entity("TrackCourse", b =>
                {
                    b.HasOne("ITIExaminationSystem.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Track_Cou__Cours__25518C17");

                    b.HasOne("ITIExaminationSystem.Models.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .IsRequired()
                        .HasConstraintName("FK__Track_Cou__Track__245D67DE");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Branch", b =>
                {
                    b.Navigation("Assigns");

                    b.Navigation("BranchManagers");

                    b.Navigation("Students");

                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Course", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("Solves");

                    b.Navigation("Teaches");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Exam", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Assigns");

                    b.Navigation("Solves");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Instructor", b =>
                {
                    b.Navigation("Assigns");

                    b.Navigation("Questions");

                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Choices");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Student", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Solves");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.Track", b =>
                {
                    b.Navigation("Assigns");

                    b.Navigation("Students");

                    b.Navigation("Teaches");
                });

            modelBuilder.Entity("ITIExaminationSystem.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("BranchManagers");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
